### ISSUE TITLE
请问运行报这个错误怎么解决

### ISSUE THREAD

**Issue by Blusez** [Jerome-MJ/chongding#2]
Traceback (most recent call last):
  File "d:/studyspace/python_/chongding-master/search.py", line 32, in <module>
    path=capture.cap()
  File "d:\studyspace\python_\chongding-master\capture.py", line 16, in cap
    img.save(path+".png")
  File "D:\Program Files\python35_64\lib\site-packages\PIL\Image.py", line 1927, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: '2018-01-13 14:39:59.png'

**Comment by Jerome-MJ** [comment]
文件权限问题好像，
windows写上全路径地址把。
